# Generated by Django 5.2.5 on 2025-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_responder_ticket_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
