# Generated by Django 5.2.5 on 2025-08-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_classified',
            field=models.BooleanField(default=False),
        ),
    ]
